catalog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # /catalog/
    url(r'^$', views.index, name='index',),

    # /departments/
    url(r'^departments/$',views.departments,name='departments'),

    # /2/category/
    url(r'^(?P<category_id>[0-9]+)/category/$',views.category,name='category'),

    # /2/subcategory/
    url(r'^(?P<subcategory_id>[0-9]+)/subcategory/',views.subcategory,name='subcategory'),

    # /3/product/
    url(r'^(?P<product_id>[0-9]+)/product/',views.product,name='product'),

    # /add-category/
    url(r'^add-category/$',views.add_category,name='add_category'),

    # /add-subcategory/
    url(r'^add-subcategory/$',views.add_subcategory,name='add_subcategory'),

    # /add-product/
    url(r'^add-product/$',views.add_product,name='add_product'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # /
    url(r'^',include('catalog.urls')),

    # /admin/
    url(r'^admin/', include(admin.site.urls)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('departments',kwargs={'pk':self.pk})

    def __str__(self):
        return self.name

class Subcategory(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    name = models.CharField(max_length=50, db_index=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Product(models.Model):
    subcategory = models.ForeignKey(Subcategory,on_delete=models.CASCADE)
    name = models.CharField(max_length=50,unique=True)
    description = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    image = models.ImageField(upload_to='Images/%Y/%m/%d', blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

catalog/forms.py
from .models import Category, Subcategory, Product
from django.forms import ModelForm, inlineformset_factory


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ["name", 'description']


class SubcategoryForm(ModelForm):
    class Meta:
        model = Subcategory
        exclude = ()

SubcategoryFormSet = inlineformset_factory(Category,Subcategory,form=SubcategoryForm,extra=1)


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ()
ProductFormSet = inlineformset_factory(Subcategory,Product,form=ProductForm,extra=1)


class UploadProductImage(ModelForm):
    class Meta:
        model = Product
        exclude = ()

catalog/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse, redirect
from django.template import loader
from .models import Category, Subcategory, Product
from .forms import CategoryForm, SubcategoryForm, ProductForm, UploadProductImage

def index(request):
    try:
        product_list = Product.objects.all()
    except Product.DoesNotExist:
        raise Http404("No Products")
    template = loader.get_template('index.html')
    context = {
        'product_list': product_list,
    }
    return HttpResponse(template.render(context, request))


def departments(request):
    try:
        department_list = Category.objects.all()
    except Category.DoesNotExist:
        raise Http404("No Departments")
    template = loader.get_template('departments.html')
    context = {
        'department_list': department_list,
    }
    return HttpResponse(template.render(context, request))


def category(request,category_id):
    try:
        category_list = Subcategory.objects.filter(category=category_id)
    except Subcategory.DoesNotExist:
        raise Http404("No Categories")
    template = loader.get_template('category.html')
    context = {
        'category_list': category_list,
    }
    return HttpResponse(template.render(context, request))


def subcategory(request,subcategory_id):
    try:
        dict = Subcategory.objects.filter(id=subcategory_id).values('category')
        c_id = dict[0]
        subcategory_list = Product.objects.filter(subcategory=subcategory_id)
    except Product.DoesNotExist:
        raise Http404("No Products")
    template = loader.get_template('subcategory.html')
    context = {
        'subcategory_list': subcategory_list,
        'c_id': c_id['category']
    }
    return HttpResponse(template.render(context, request))


def product(request, product_id):
    try:
        product_details = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        raise Http404("Product does not exist")
    template = loader.get_template('product.html')
    context = {
        'product_details': product_details,
    }
    return HttpResponse(template.render(context, request))


def add_category(request):
    title = 'Add New Category'
    form_class = CategoryForm
    if request.method == 'POST':
        form = form_class(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('departments')
    return render(request, 'add_new.html', {'form_class': form_class, 'title':title})


def add_subcategory(request):
    title = 'Add New SubCategory'
    form_class = SubcategoryForm
    if request.method == 'POST':
        form = form_class(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    return render(request, 'add_new.html', {'form_class': form_class, 'title': title})


def add_product(request):
    title = 'Add New Product'
    if request.method == 'POST':
        form = UploadProductImage(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
    form_class = UploadProductImage
    return render(request, 'add_new.html', {'form_class': form_class, 'title': title})

catalog/templates/add_new.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-4 col-md-offset-2 main">
    <h2 class="sub-header">{{ title }}</h2>
        <p>{{ form.fieldname.errors.as_text }}</p>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in form_class.visible_fields %}
                <div class="form_class-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                    {% for error in field.errors %}
                      <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            {% endfor %}
            <br>
            <button type="submit" value="submit">Submit</button>
        </form>
    </div>

{% endblock %}

catalog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <link rel="icon" href="https://static.roikoi.com/refer/static/8fe0a5e1/favicon.ico">

    <title>Django Catalog application</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-027974239566/dashboard.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
              <a class="navbar-brand" href="{% url 'index' %}">Django Catalog application</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/admin/">Admin Dashboard</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            {% include "sidebar.html" %}
        </div>
        <div>
            {% block content %}
            {% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
  </body>
</html>

catalog/templates/category.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-5 col-md-offset-2 main">
    <h2 class="sub-header">Subcategories</h2>
        <ul class="list-group">
            {% for c in category_list %}
                <li class="list-group-item"><a href="{% url 'subcategory' c.id %}">{{ c.name }}</a> - {{ c.description }}
                <span class="badge">{{ c.product_set.count }}</span></li>
            {% endfor %}
        </ul>
    <a class="btn btn-default" href="{% url 'departments' %}" role="button">Back</a>
    </div>

{% endblock %}

catalog/templates/category_form.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-5 col-md-offset-2 main">
    <h2 class="sub-header">New Category</h2>
        <div class="form-group">
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


        </div>
    </div>
{% endblock %}

catalog/templates/departments.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-5 col-md-offset-2 main">
    <h2 class="sub-header">Category</h2>
        <ul class="list-group">
            {% for d in department_list %}
                <li class="list-group-item"><a href="{% url 'category' d.id %}">{{ d.name }}</a> - {{ d.description }}
                <span class="badge">{{ d.subcategory_set.count }}</span>
                </li>
            {% endfor %}
        </ul>
    <a class="btn btn-default" href="{% url 'index' %}" role="button">Back</a>
    </div>


{% endblock %}

catalog/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Catalog</h1>

          <div class="row placeholders">
              {% for p in product_list %}
                    <div class="col-xs-6 col-sm-3 thumbnail">
                        <img src="/media/{{ p.image }}" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                        <h4><a href="{% url 'product' p.id %}">{{ p.name }}</a></h4>


                        <div style="text-align:center"><p style="text-align: justify"><span class="text-muted">{{ p.info }}</span></p></div>
                        <a href="{% url 'category' p.subcategory.category.id %}" class="btn btn-primary" role="button">{{ p.subcategory.category }}</a>
                        <a href="{% url 'subcategory' p.subcategory.id %}" class="btn btn-default" role="button">{{ p.subcategory }}</a>
                        <span class="badge"><span class="glyphicon glyphicon-usd" aria-hidden="true">{{ p.price }}</span></span>
                    </div>
                {% endfor %}
          </div>
        </div>
{% endblock %}

catalog/templates/product.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-5 col-md-offset-2 main">
    <h2 class="sub-header">Product Details</h2>

    <div class="row">
        <div class="col-sm-12 col-md-8">
            <div class="thumbnail" style="text-align:center;">
            <img src="/media/{{ product_details.image }}" alt="{{ p.name }} thumbnail">
            <div class="caption">
            <h3>{{ product_details.name }}</h3>
            <p>{{ product_details.description }}</p>

            </div>
            <p>
            Created: {{ product_details.created }} <br>
            Updated: {{ product_details.updated }}
            </p>
            <p>
                <a href="{% url 'category' product_details.subcategory.category.id %}" class="btn btn-primary" role="button">category</a>
                <a href="{% url 'subcategory' product_details.subcategory.id %}" class="btn btn-default" role="button">Subcategory</a>
                <span class="badge"><span class="glyphicon glyphicon-usd" aria-hidden="true">{{ product_details.price }}</span></span>
            </p>
            </div>
        </div>
    </div>

    </div>

{% endblock %}

catalog/templates/sidebar.html
{% block sidebar %}
    <ul class="nav nav-sidebar">
	    <li><a href="{% url 'departments' %}">Categories</a></li>
    </ul>

    <ul class="nav nav-sidebar">
        <li><a href="{% url 'add_category' %}">Add Category</a></li>
        <li><a href="{% url 'add_subcategory' %}">Add Subcategory</a></li>
        <li><a href="{% url 'add_product' %}">Add Product</a></li>
    </ul>
{% endblock %}

catalog/templates/subcategory.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-5 col-md-offset-2 main">
    <h2 class="sub-header">Products</h2>
        <ul class="list-group">
            {% for s in subcategory_list %}
                <li class="list-group-item"><a href="{% url 'product' s.id %}">{{ s.name }}</a></li>
            {% endfor %}
        </ul>
    <a class="btn btn-default" href="{% url 'category' c_id %}" role="button">Back</a>
    </div>

{% endblock %}